version: "3.1"
services:
  pms-database-mariadb:
    image: mariadb:11.5.2
    container_name: pms-database-mariadb
    hostname: pms-database-mariadb
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=pms
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./data:/var/lib/mysql

  pms-nginx:
    image: nginx:alpine
    container_name: pms-nginx
    hostname: pms-nginx
    working_dir: /application
    restart: always
    tty: true
    volumes:
      - .:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8002:80"

  pms-php-fpm:
    build: ./docker/php-fpm
    container_name: pms-php-fpm
    hostname: pms-php-fpm
    # Executing original entrypoint, else php won't work, then executing my entrypoint and finally run the php-fpm thus also keep container alive
    entrypoint: sh -c "/usr/local/bin/docker-php-entrypoint && touch /tmp/log.log && php-fpm"
    working_dir: /application
    restart: always
    tty: true
    depends_on:
      - pms-database-mariadb
      - pms-nginx
    volumes:
      - .:/application

  pms-adminer:
    container_name: pms-adminer
    hostname: pms-adminer
    image: adminer
    restart: always
    tty: true
    ports:
      - 8081:8080